### PR TITLE
redshift

### PR DESCRIPTION
**Pull request by bubba082683**
Amazon is complete vertica still needs some work

### CODE REVIEW

**Comment by williamdubberley** [comment]
in the deployment guide everything is a source, remember this is for Oracle engineers, so target will be oracle products, we will amend the guide later with a list of data sources that can be sources and targets

**Comment by bubba082683** [comment]
There are some data sources that are only targets not sources. Amazon Redshift does not work as a source. I am going to create a case for that to be resolved

**Review by williamdubberley — CHANGES_REQUESTED** [review]
ther is too much data in the logon section. minimum information necessary, should match the required information

**Comment by bubba082683** [comment]
I updated this a few days ago it needs a review

**Review by williamdubberley — CHANGES_REQUESTED** [review]
on reshift and vertica, those need to say source not target, redshift  has too much unnecessary data.
if for some reason data can not be extracted from these that is a development issue and needs to be corrected. but this deployment guide is directed at oracle, so ALL datassources are "sources"

**Comment by bubba082683** [comment]
Still need to eliminate data that is not needed as a source.

**Review by williamdubberley — APPROVED** [review]

**Pull request merged**
